### ISSUE TITLE
Log is full of error messages. Proxy module issue?

### ISSUE THREAD

**Issue by molind** [realm/realm-object-server#203]
## Goals

Make sure that everything is OK.

## Expected Results

Log contains minimum of errors and it's clean what's happened and how to fix it.

## Actual Results

Log is full of errors (see below). Seems proxy is overloaded. Or realm server itself is overloaded and it won't accept connection or failed to deliver results.

## Steps to Reproduce

We have 50Gb of user_data by now. And around 500 users online avg.

## Code Sample

None.

## Version of Realm and Tooling

- Realm Object Server Version: 1.7.2
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: Ubuntu 16.04 inside Docker
- Client SDK Version: 2.5.0
- Client OS & Version: iOS 8-9-10

## Logs

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
2017-05-29T12:56:37.107Z - info: sync-server: Sync Connection[1292]: Session[1799]: Received: IDENT(server_file_ident=2183434214224649132, client_file_ident=1, client_file_ident_secret=7545865002343459623, scan_server_version=566, scan_client_version=1088, latest_server_version=566, latest_server_session_ident=6114730031468925294)
2017-05-29T12:56:37.267Z - warn: [syncProxy] internal error: Error: connect ETIMEDOUT 127.0.0.1:27800
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14).
2017-05-29T12:56:37.267Z - error: client: Connection[2097]: Writing failed: End of input
2017-05-29T12:56:37.268Z - info: client: Connection[2097]: Connection closed due to error
2017-05-29T12:56:37.268Z - info: client: Connection[2097]: Resolving '0.0.0.0:9080'
2017-05-29T12:56:37.269Z - info: client: Connection[2097]: Connecting to endpoint '0.0.0.0:9080' (1/1)
2017-05-29T12:56:37.269Z - info: client: Connection[2097]: Connected to endpoint '0.0.0.0:9080' (from '127.0.0.1:59570')
2017-05-29T12:56:37.523Z - warn: [syncProxy] internal error: Error: connect ETIMEDOUT 127.0.0.1:27800
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14).
2017-05-29T12:56:37.524Z - error: client: Connection[84]: Writing failed: End of input
2017-05-29T12:56:37.524Z - info: client: Connection[84]: Connection closed due to error
2017-05-29T12:56:37.525Z - info: client: Connection[84]: Resolving '0.0.0.0:9080'
2017-05-29T12:56:37.525Z - info: client: Connection[84]: Connecting to endpoint '0.0.0.0:9080' (1/1)
2017-05-29T12:56:37.525Z - info: client: Connection[84]: Connected to endpoint '0.0.0.0:9080' (from '127.0.0.1:59574')
2017-05-29T12:56:37.775Z - info: sync-server: HTTP Connection[1294]: Received: Sync HTTP request(protocol_version=18)
2017-05-29T12:56:37.779Z - warn: [syncProxy] internal error: Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:572:26).
  </code>
</details>

**Comment by molind** [comment]
Full log attached. Somewhere in the middle of log I changed listen addresses from `::` to `0.0.0.0`

[realm-object-server.log.zip](https://github.com/realm/realm-mobile-platform/files/1035855/realm-object-server.log.zip)

**Comment by bigfish24** [comment]
Sorry about this. I think this is related to a known issue of which we have an upcoming release that should address it. However, will assign to another engineer to verify.

**Comment by morten-krogh** [comment]
@molind 

There are two issues here.

One issue is that the system is overloaded or fails for some reasons.
The other issue is that our logging is bad at pinpointing the problems.

Regarding the failures themselves, I can study your logs to figure out what is happening. 

Regarding the logging, we will very soon rethink and redo our system. We will make the
log output much more readable and informative. However, it will take some time before we have a better logging system out.

Would you like me to look closer into your current server issues? 
For that it would help to turn on debug level logging.

**Comment by molind** [comment]
@morten-krogh yes, please. There is my debug-level log file after realm startup. 

https://www.dropbox.com/s/t3a0axow0l5uapz/realm-object-server%202.log.zip?dl=0

**Comment by morten-krogh** [comment]
@molind Thanks, I will look at it.
