### ISSUE TITLE
ROS (v2.0.8) fails to start 

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [realm/realm-object-server#285]
I have just completed a fresh install of ROS v2 onto a Digital Ocean Ubuntu 16.04 droplet.

When I start ROS : `ros start` I get the following output.

```
ros-admin@service:~$ ros start
Error: Cannot find module 'del'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ros-admin/.nvm/versions/node/v6.11.5/lib/node_modules/realm-object-server/dist/TestServer.js:14:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
ros-admin@service:~$ 
```

I notice that NPM is v6.11.5 - this was the default installed with the droplet.

Ideas?

## Version of Realm and Tooling
- Realm Object Server Version: 2.0.8 - Developer
- Ubuntu 16.04.3 (Digital Ocean)

**Comment by ianbradbury-bizzibody** [comment]
I see 2.0.9 has *just* been released.

How do I upgrade?  I can't see anything in the docs on how to upgrade (and I nothing about NPM)

**Comment by ianbradbury-bizzibody** [comment]
Figured it out.

**Comment by ianbradbury-bizzibody** [comment]
I've upgraded to 2.0.9.

Similar problem - different error message.

```
ros-admin@service:~$ ros start
TypeError: Class extends value undefined is not a function or null
    at Object.<anonymous> (/home/ros-admin/.nvm/versions/node/v6.11.5/lib/node_modules/realm-object-server/dist/TestServer.js:15:39)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ros-admin/.nvm/versions/node/v6.11.5/lib/node_modules/realm-object-server/dist/index.js:14:10)
    at Module._compile (module.js:570:32)
ros-admin@service:~$ npm start ros

```

**Comment by bigfish24** [comment]
Seems like your npm install is (silently) failing. What are the specs?

**Comment by ianbradbury-bizzibody** [comment]
I have upgraded to 2.0.10 and the server starts.  

However... the server will not recognise HTTPS.

My `src/index.ts` script looks like this:
```
const BasicServer = require('realm-object-server').BasicServer
const path = require('path')
const server = new BasicServer()

server.start({
        dataPath: path.join(__dirname, '../data'),
        httpsEnabled: true,
        httpsKey: '/etc/letsencrypt/live/{my domain}/privkey.pem',
        httpsCert: '/etc/letsencrypt/live/{my domain}/cert.pem',
        httpsPort: 9443
    })
    .then(() => {
        console.log(`# Your server is started `, server.address)
    })
    .catch(err => {
        console.error(`There was an error starting your file`)
    })

```

And the server outputs this:
```
info: Realm Object Server version 2.0.4 is starting
info: Realm sync server started ([realm-core-4.0.2], [realm-sync-2.0.2]) service=sync
info: Directory holding persistent state: /home/ros_admin/bb/data/sync/user_data service=sync
info: Operating mode: master_with_no_slave service=sync
info: Listening on 127.0.0.1:38876 (sync protocol version 22) service=sync
info: sync-client: Connection[1]: Connected to endpoint '127.0.0.1:38876' (from '127.0.0.1:38708')
info: sync-client: Connection[2]: Connected to endpoint '127.0.0.1:38876' (from '127.0.0.1:38710')
info: sync-client: Connection[3]: Connected to endpoint '127.0.0.1:38876' (from '127.0.0.1:38712')
info: Starting auth provider 'password'
info: sync-client: Connection[4]: Connected to endpoint '127.0.0.1:38876' (from '127.0.0.1:38714')
info: 127.0.0.1 - GET /realms/files/%2F__admin HTTP/1.1 200 41 - 7.631 ms
info: 127.0.0.1 - GET /realms/files/%2F__revocation HTTP/1.1 200 46 - 1.026 ms
info: 127.0.0.1 - GET /realms/files/%2F__wildcardpermissions HTTP/1.1 200 55 - 1.304 ms
info: 127.0.0.1 - GET /realms/files/%2F__password HTTP/1.1 200 44 - 0.450 ms
info: Realm Object Server has started and is listening on http://0.0.0.0:9080
# Your server is started  0.0.0.0:9080
info: sync-client: Connection[5]: Connected to endpoint '0.0.0.0:9080' (from '127.0.0.1:35720')
info: sync-client: Connection[6]: Connected to endpoint '0.0.0.0:9080' (from '127.0.0.1:35724')

```

Because the documentation on these scripts is light - likely I have a syntax error.

**Comment by bigfish24** [comment]
You syntax looks ok, but I think you upgraded the global `realm-object-server`. To upgrade your project you will need to `cd MyApp (or whatever)` and then run `npm install realm-object-server` to update the `node_modules` for the project. We are working on a guide to dramatically improve our docs, thanks for bearing with us!

**Comment by morten-krogh** [comment]
I think it is 
"https: true"
instead of
"httpsEnabled: true".

**Comment by morten-krogh** [comment]
And
 "httpsKeyPath" instead of "httpsKey"
 "httpsCertChainPath" instead of "httpsCert".

I got the server to start with https. It should work for you.

**Comment by Fjalmari** [comment]
I also had the similar problem and I'm not very familiar with node so I decided to share my working setup with https:

### Note:
I created the project with `ros init <name> --template js`

#### ./src/index.js
```
const BasicServer = require('realm-object-server').BasicServer
const path = require('path')
const server = new BasicServer()
// Missing modules
const PasswordAuthProvider = require('realm-object-server/dist/auth/password').PasswordAuthProvider
const FacebookAuthProvider = require('realm-object-server/dist/auth/facebook').FacebookAuthProvider

// Authentication methods
let username = new PasswordAuthProvider(
  {
    autoCreateAdminUser: true,
    saltLength: 32,
    iterations: 10000,
    keyLength: 512,
    digest: "sha512"
  }
)
let facebook = new FacebookAuthProvider()

// Launch server
server.start({
        dataPath: path.join(__dirname, '../data'),
        authProviders: [ username, facebook ],
        // HTTPS setup
        https: true,
        httpsPort: 9443,
        httpsKeyPath: '<absolute path to key.pem>',
        httpsCertChainPath: '<absolute path to chained cert.pem>'
    })
    .then(() => {
        console.log(`Your server is started `, server.address)
    })
    .catch(err => {
        // Print the error which pointed me to
        // node-modules/realm-object-server/dist/Server.js L562 where I again printed the error log
        // to see that key and cert paths gave ENOENT -> changed to absolute path and it worked
        console.error(`There was an error starting your file: `, err)
    })
```

And launch the project with pm2 from project folder:
`pm2 start ./src/index.js --name <project-name>`

**Comment by ianbradbury-bizzibody** [comment]
My word!

**IT WORKS!**

Thanks @morten-krogh @Fjalmari - Your help was invaluable.
