### ISSUE TITLE
Error: Cannot find module '/usr/local/lib/node_modules/realm-object-server/node_modules/realm/compiled/node-v59_darwin_x64/realm.node'

### ISSUE THREAD

**Issue by michaelcordero** [realm/realm-object-server#323]
## Goals

Initialize realm object server.

## Expected Results

Realm object server command to create a realm server.

## Actual Results

module.js:544
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/realm-object-server/node_modules/realm/compiled/node-v59_darwin_x64/realm.node'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/realm-object-server/node_modules/realm/lib/index.js:102:28)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)

## Steps to Reproduce

1. npm install -g realm-object-server
2. ros init myapp

## Version of Realm and Tooling

- Realm Object Server Version: Latest
- Flavor:
  - [X ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6) Mac OS High Sierra 10.13.2
- Client SDK Version: ? 
- Client OS & Version: ?

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    Paste output here
  </code>
</details>

**Comment by michaelcordero** [comment]
Following the pre-requisites installation [instructions](https://realm.io/docs/realm-object-server/latest/#install-realm-object-server) resolved this. Please close this issue.
