### ISSUE TITLE
Cannot install realm-object-server

### ISSUE THREAD

**Issue by nojvek** [realm/realm-object-server#349]
Spent two hours trying to install ros.

Upgraded node version, uninstalled node-gyp and node-pre-gyp. 

```
sudo npm install -g realm-object-server
/usr/bin/ros -> /usr/lib/node_modules/realm-object-server/dist/cli.js

> realm@1.12.0 install /usr/lib/node_modules/realm-object-server/node_modules/realm-one/node_modules/realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://static.realm.io/node-pre-gyp/1.12.0/realm-v1.12.0-node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@1.12.0 and node@8.9.4 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/realm-object-server/node_modules/realm-one/node_modules/realm/build'
gyp ERR! System Linux 4.4.0-67-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/
lib/node_modules/realm-object-server/node_modules/realm-one/node_modules/realm/compiled/node-v57_linux_x64/realm.node" "--module_name=realm" "--modu
le_path=/usr/lib/node_modules/realm-object-server/node_modules/realm-one/node_modules/realm/compiled/node-v57_linux_x64"
gyp ERR! cwd /usr/lib/node_modules/realm-object-server/node_modules/realm-one/node_modules/realm
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/realm-object-server/node_modules/realm-one/node_modules/realm/compiled/node-v57_linux_x64/realm.node --module_name=realm --module_path=/usr/lib/node_modules/realm-object-server/node_modules/realm-one/node_modules/realm/compiled/node-v57_linux_x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/realm-object-server/node_modules/realm-one/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.4.0-67-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/realm-object-server/node_modules/realm-one/node_modules/.bin/node-pre-gyp" "install
```

Its a mystery why 8.9.4 doesn't have a prebuilt version. It's a LTS version. Or why ros can't just build itself. I checked permissions and they are all fine too.

Haaaaaaalp!

**Comment by nirinchev** [comment]
What operating system are you installing on?

**Comment by nojvek** [comment]
Mac

**Comment by bmunkholm** [comment]
@nojvek We have deprecated the Developer Edition, so I would propose you try out Cloud (https://cloud.realm.io) instead. That works instantly :-)

**Comment by nojvek** [comment]
Tried to figure it out, but didn't quite work. I wish it was as simple as setting up mysql-server with a simple apt-get install, but I've spent way too many hours battling realm-object-server so I guess I'll use something less painful.
