### ISSUE TITLE
Cannot find module 'realm-object-server'

### ISSUE THREAD

**Issue by artutra** [realm/realm-object-server#414]
## Steps to Reproduce

Just follow the instructions on the Getting Started Enterprise
https://github.com/realm/realm-object-server/tree/master/getting-started-enterprise

## Version of Realm and Tooling

- Flavor:
  - [ ] Cloud
  - [x] Self-hosted Enterprise
- Server OS & Version: Ubuntu 16.04
- Docker Version:
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```
## Logs

<details>
  <summary>docker-compose up</summary>
</details>

And then all ROS containers log the bellow:
```
auth_1               | module.js:471
auth_1               |     throw err;
auth_1               |     ^
auth_1               | 
auth_1               | Error: Cannot find module 'realm-object-server'
auth_1               |     at Function.Module._resolveFilename (module.js:469:15)
auth_1               |     at Function.Module._load (module.js:417:25)
auth_1               |     at Module.require (module.js:497:17)
auth_1               |     at require (internal/module.js:20:19)
auth_1               |     at Object.<anonymous> (/usr/local/lib/node_modules/realm-object-server-enterprise/dist/EnterpriseServer.js:14:13)
auth_1               |     at Module._compile (module.js:570:32)
auth_1               |     at Object.Module._extensions..js (module.js:579:10)
auth_1               |     at Module.load (module.js:487:32)
auth_1               |     at tryModuleLoad (module.js:446:12)
auth_1               |     at Function.Module._load (module.js:438:3)
```

**Comment by bmunkholm** [comment]
@artutra Sorry, we have deprecated those instructions now. You should have a look at https://docs.realm.io/server/installation and get in touch with support for getting access to the server.
