### ISSUE TITLE
changeset: Schema mismatch - realm::sync::Client::Error:112

### ISSUE THREAD

**Issue by sshakilms** [realm/realm-object-server#416]
getting same error : its  happening on only ReamList<String> 

Schema 
```
    private RealmList<String> specialization;
    private String speciality;
    private RealmList<String> links;
  
```

```
@RealmModule(classes={
        SpecialistEntity.class,
        SpecialtyEntity.class})
public class LoopHealthSchema {
}
```

```
 if (realmSyncConfig == null) {
                    realmSyncConfig = user.createConfiguration(RealmServerConfig.REALM_Common_URL+"realm-admin/loopHealthUser")
                            .schemaVersion(1)
                            .modules(new LoopHealthSchema())
                            .errorHandler((session, error) -> {
                                error.printStackTrace();
                                Timber.e("User error:%s", error.getErrorCode());
                                //EventBus.getDefault().post(new RealmRefreshModel(ChatServer.Realm_Reset_Sync,true,error));
                                //myCustomObject.onObjectError("Realm Error Found");
                            })
                            .build();
                }
                //set Default Instance
                realmConfiguration = realmSyncConfig;
```

error logs
```

E/REALM_SYNC: Connection[8]: Session[8]: Failed to transform received changeset: Schema mismatch: Property 'specialization' in class 'SpecialistEntity' is nullable on one side and not on the other.
2019-03-19 17:00:11.713 14536-14652/com.invoqhealth.loophealth2 W/System.err: CLIENT_BAD_CHANGESET(realm::sync::Client::Error:112): Bad changeset (DOWNLOAD)
2019-03-19 17:00:11.714 14536-14652/com.invoqhealth.loophealth2 W/System.err:     at io.realm.SyncSession.notifySessionError(SyncSession.java:246)
2019-03-19 17:00:11.714 14536-14652/com.invoqhealth.loophealth2 W/System.err:     at io.realm.SyncManager.notifyErrorHandler(SyncManager.java:519)
2019-03-19 17:00:11.715 14536-14652/com.invoqhealth.loophealth2 E/RealmService: User error:CLIENT_BAD_CHANGESET(realm::sync::Client::Error:112)
```
SDK - 5.9.0

**Comment by sshakilms** [comment]
on my Observation this happening becoz my old Schema have " RealmList<String> name " i m not declare @required but now when RealmPartial File Create in Schema There is no Optional declare .

based on RealmDashboard ?-Optional in Main Realm File and on Partial FIles There is no ? 
Question is why now PartalFiles are created without ? of Realm List (Required or nullability)

**Comment by nirinchev** [comment]
This was due to a server side bug that was resolved on Thursday. Please try again and let us know if you still see this issue.

**Comment by juanda2222** [comment]
Still have this issue with Kotlin client
