### ISSUE TITLE
Can not access Realm

### ISSUE THREAD

**Issue by namtran303** [realm/realm-object-server#443]
Hi Realm team support,

I’m implementing realm on android and I get issue on realm SDK

Fatal Exception: io.realm.exceptions.RealmException: Exception happens when initializing Realm in the background thread.
       at io.realm.BaseRealm$InstanceCallback.onError(BaseRealm.java:874)
       at io.realm.Realm$Callback.onError(Realm.java:1843)
       at io.realm.RealmCache$CreateRealmRunnable$2.run(RealmCache.java:169)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

Caused by io.realm.ObjectServerError
       at io.realm.SyncSession$WaitForSessionWrapper.throwExceptionIfNeeded(SyncSession.java:728)
       at io.realm.SyncSession.waitForChanges(SyncSession.java:427)
       at io.realm.SyncSession.downloadAllServerChanges(SyncSession.java:353)
       at io.realm.internal.SyncObjectServerFacade.downloadRemoteChanges(SyncObjectServerFacade.java:166)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:302)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
       at io.realm.RealmCache$CreateRealmRunnable.run(RealmCache.java:115)
       at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

I tried to reproduce issue but I can not.I think issue happen when have many access to realm.
Could you please help me check the issue?

Currently, I using 'io.realm:realm-gradle-plugin:4.3.2'
If you need more information pls let me know.

Thanks & regards,

Nam

**Comment by bmunkholm** [comment]
Hi @namtran303 
Could I ask you to please create that issue in realm-java instead (using the issue template provided there). Thanks!
