### ISSUE TITLE
REALM_JNI: Exception has been thrown: Column name too long Exception backtrace

### ISSUE THREAD

**Issue by gopi-krishna-1086** [realm/realm-object-server#448]
E/REALM_JNI: jni: ThrowingException 8, Column name too long
    Exception backtrace:
    <backtrace not supported on this platform>, .
E/REALM_JNI: Exception has been thrown: Column name too long
    Exception backtrace:
    <backtrace not supported on this platform>
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.realm, PID: 16215
    java.lang.IllegalStateException: Column name too long
    Exception backtrace:
    <backtrace not supported on this platform>
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:172)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:248)
        at io.realm.BaseRealm.<init>(BaseRealm.java:138)
        at io.realm.BaseRealm.<init>(BaseRealm.java:105)
        at io.realm.Realm.<init>(Realm.java:159)
        at io.realm.Realm.createInstance(Realm.java:495)
        at io.realm.RealmCache.createInstance(RealmCache.java:481)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:448)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
        at io.realm.Realm.getInstance(Realm.java:424)
        at com.example.realm.DataActivity.lambda$onCreate$0$DataActivity(DataActivity.java:51)
        at com.example.realm.-$$Lambda$DataActivity$bjO-36fiVhzIdStkrFyM9NATF5g.onResult(Unknown Source:2)
        at io.realm.internal.mongodb.Request$3.run(Request.java:90)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:211)
        at android.app.ActivityThread.main(ActivityThread.java:7234)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)

**Comment by bmunkholm** [comment]
@gopi-krishna-1086 Would you mind posting this in realm-java repo instead?
But before you do, please provide some more detailed information.
The exception basically say that one of your property names is too long. So the first question is if you have some very long property names? You appear to hit a limitation rather than a bug.
